name: Build Windows Portable App

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Convert icon.png to icon.ico if present
      shell: bash
      run: |
       if [ -f icon.png ]; then
         echo "icon.png found. Resizing to square and converting..."
         npx --yes sharp-cli resize 256 256 --fit contain --background "rgba(0,0,0,0)" -i icon.png -o icon_square.png
         npx --yes png-to-ico icon_square.png > icon.ico
       fi


    - name: Install dependencies
      run: npm install

    - name: Build Windows App
      run: npm run build:win

    - uses: actions/upload-artifact@v4
      with:
         name: reha-work-manager-windows-exe
         path: dist/*.exe
         if-no-files-found: error
